services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: apibuklitoprocess
    ports:
      - "8080:8080"
    environment:
      - PathBase=/buk
    env_file:
      - .env
    restart: unless-stopped
    extra_hosts:
      - "host.docker.internal:host-gateway"
    
